version: '3.8'
 
services:
  php:
    build: .
    image: php8-apache
    #image: httpd
    container_name: php-apache
    ports:
      - "7880:80"
    #volumes:
    #  - ./t37import:/var/www/html/
    #command: /bin/apache2 -D FOREGROUND

  web:
    image: nginx
    container_name: frontend8081
    volumes:
     - ./frontend:/usr/share/nginx/html
    ports:
     - "8081:80"
  
  db:
    image: mysql:5.7
    container_name: db3306
    environment:
      MYSQL_ROOT_PASSWORD: R00tPassword!
      MYSQL_DATABASE: task37
      MYSQL_USER: digiprime
      MYSQL_PASSWORD: Horizon2020
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma8082
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    restart: always
    ports:
      - 8082:80
  
  task37api:
    image: node
    container_name: task37api9300
    build: .
    #volumes:
    # - ./script:/script
    command: node /usr/app/task37api.js 
    ports:
     - "9300:9300"

  sankeyapi:
    image: node
    container_name: sankeyapi9200
    build: .
    #volumes:
    # - ./script:/script
    command: node /usr/app/sankey.js
    ports:
     - "9200:9200"


volumes:
  dbdata:
